/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:c19bec8caead4f6d057e712a87a9b881:f33586e05b06cca817ec12712be8f035:905072b72ea92acf8fa5b0216a681f3c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class buildingAtlas
	{
		public const string Brewery = "brewery";
		public const string Farm0 = "farm0";
		public const string Farm1 = "farm1";
		public const string Farm2 = "farm2";
		public const string Farm4 = "farm4";
		public const string House = "house";
		public const string House0 = "house0";
		public const string House1 = "house1";
		public const string House2 = "house2";
		public const string House4 = "house4";
		public const string House5 = "house5";
		public const string House6 = "house6";
		public const string House7 = "house7";
		public const string House8 = "house8";
		public const string LargeSelect = "largeSelect";
		public const string Quarry = "quarry";
		public const string Scientist = "scientist";
		public const string SmallSelect = "smallSelect";
		public const string Storage = "storage";
		public const string Tavern = "tavern";
		public const string Townhall = "townhall";
		public const string Woodcutter4 = "woodcutter4";
	}
}