/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:94eb52befd173b5e04aac2fc5544f615:173b5950989d54680b15ae735f0333ac:e54b12530905a7f2f23d43a9b4c7e53a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class interactiveAtlas
	{
		public const string Tree = "tree";
	}
}