/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:76584af45907cf82a97d6cbcfa21c1a6:8adc7d1885681f7c36686bb5400d8d0a:e54b12530905a7f2f23d43a9b4c7e53a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class interactiveAtlas
	{
		public const string Tree = "tree";
		public const string Tree2 = "tree2";
		public const string Tree3 = "tree3";
	}
}