/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:ce8aed685eb979e41f1b7a45d1e657cd:09f9352208a628a442a68677926a3a3f:e54b12530905a7f2f23d43a9b4c7e53a$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class interactiveAtlas
	{
		public const string Stones = "stones";
		public const string Tree = "tree";
		public const string Tree2 = "tree2";
		public const string Tree3 = "tree3";
	}
}