/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:b1b0eab84c0af603eec25b7c8f95ac6d:b56590b340a89447042bfb08d9ebd497:bd0f4c71b5cb59f99b3ec3385caa636d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class menuAtlas
	{
		public const string Buttonfarm = "buttonfarm";
		public const string Buttonfarmland = "buttonfarmland";
		public const string Buttonhouse = "buttonhouse";
		public const string Buttonquarry = "buttonquarry";
		public const string Buttonroad = "buttonroad";
		public const string Buttonscientist = "buttonscientist";
		public const string Buttonstorage = "buttonstorage";
		public const string Buttontownhall = "buttontownhall";
		public const string Buttonwoodcutter = "buttonwoodcutter";
		public const string Menu1 = "menu1";
	}
}