/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:2a1d686be974a61abea25bd848c0b4f4:0ccfc19f96c2d96c479571e5dcbee5f3:bd0f4c71b5cb59f99b3ec3385caa636d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class menuAtlas
	{
		public const string Buttonfarm = "buttonfarm";
		public const string Buttonfarmland = "buttonfarmland";
		public const string Buttonhouse = "buttonhouse";
		public const string Buttonquarry = "buttonquarry";
		public const string Buttonroad = "buttonroad";
		public const string Buttonscientist = "buttonscientist";
		public const string Buttonstorage = "buttonstorage";
		public const string Buttontownhall = "buttontownhall";
		public const string Buttonwoodcutter = "buttonwoodcutter";
		public const string ContinueButton = "continueButton";
		public const string Menu1 = "menu1";
		public const string Menu2 = "menu2";
		public const string Menu3 = "menu3";
		public const string QuitButton = "quitButton";
		public const string StartButton = "startButton";
	}
}