/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:adacc5834d620fb1253224dde28493c4:9aa7c3a877c41d6aac517646e307435e:bd0f4c71b5cb59f99b3ec3385caa636d$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class menuAtlas
	{
		public const string Buttonfarm = "buttonfarm";
		public const string Buttonfarmland = "buttonfarmland";
		public const string Buttonhouse = "buttonhouse";
		public const string Buttonquarry = "buttonquarry";
		public const string Buttonroad = "buttonroad";
		public const string Buttonscientist = "buttonscientist";
		public const string Buttonstorage = "buttonstorage";
		public const string Buttontownhall = "buttontownhall";
		public const string Buttonwoodcutter = "buttonwoodcutter";
		public const string ContinueButton = "continueButton";
		public const string Food = "food";
		public const string Gold = "gold";
		public const string Menu3 = "menu3";
		public const string Pop = "pop";
		public const string QuitButton = "quitButton";
		public const string StartButton = "startButton";
		public const string Stone = "stone";
		public const string Wood = "wood";
		public const string Workers = "workers";
	}
}