/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:85c3a5d13faeb835557518804f672527:628cf6e10a1b2d517486cc3219de11c1:51cb6b9703fb07bbaf5df13833054158$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class peopleAtlas
	{
		public const string Peop1 = "peop1";
		public const string Peop2 = "peop2";
		public const string Peop3 = "peop3";
	}
}