/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:9054dc75462a080ec001954ac5b74a40:3f82b41c9292ab67ca830c754805afeb:15e80e53d973510bcd3d7c2616e35315$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class texturePackerSpriteAtlas
	{
		public const string Grass1 = "grass1";
		public const string GrassStoneLeft = "grassStoneLeft";
		public const string GrassStoneRight = "grassStoneRight";
		public const string GrassStoneTop = "grassStoneTop";
		public const string GrassStoneTopLeft = "grassStoneTopLeft";
		public const string GrassStoneTopRight = "grassStoneTopRight";
		public const string GrassStoneTopRightLeft = "grassStoneTopRightLeft";
		public const string Sand1 = "sand1";
		public const string SandGrassAll = "sandGrassAll";
		public const string SandGrassDown = "sandGrassDown";
		public const string SandGrassDownLeft = "sandGrassDownLeft";
		public const string SandGrassDownLeftRight = "sandGrassDownLeftRight";
		public const string SandGrassDownRight = "sandGrassDownRight";
		public const string SandGrassLeft = "sandGrassLeft";
		public const string SandGrassRight = "sandGrassRight";
		public const string SandGrassTop = "sandGrassTop";
		public const string SandGrassTopDownLeft = "sandGrassTopDownLeft";
		public const string SandGrassTopDownRight = "sandGrassTopDownRight";
		public const string SandGrassTopLeft = "sandGrassTopLeft";
		public const string SandGrassTopLeftRight = "sandGrassTopLeftRight";
		public const string SandGrassTopRight = "sandGrassTopRight";
		public const string SandStoneLeft = "sandStoneLeft";
		public const string SandStoneRight = "sandStoneRight";
		public const string SandStoneTop = "sandStoneTop";
		public const string SandStoneTopLeft = "sandStoneTopLeft";
		public const string SandStoneTopRight = "sandStoneTopRight";
		public const string SandStoneTopRightLeft = "sandStoneTopRightLeft";
		public const string Stone1 = "stone1";
		public const string StreetCross = "streetCross";
		public const string StreetDownLeft = "streetDownLeft";
		public const string StreetDownRight = "streetDownRight";
		public const string StreetHori = "streetHori";
		public const string StreetLeftRightDown = "streetLeftRightDown";
		public const string StreetLeftUpDown = "streetLeftUpDown";
		public const string StreetUpLeft = "streetUpLeft";
		public const string StreetUpRight = "streetUpRight";
		public const string StreetUpRightDown = "streetUpRightDown";
		public const string StreetUpRightLeft = "streetUpRightLeft";
		public const string StreetVerti = "streetVerti";
		public const string Water1 = "water1";
		public const string WaterGrassLeft = "waterGrassLeft";
		public const string WaterGrassRight = "waterGrassRight";
		public const string WaterGrassTop = "waterGrassTop";
		public const string WaterSandTop = "waterSandTop";
		public const string WaterStoneTop = "waterStoneTop";
	}
}